apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: production
  labels:
    app: my-app
    environment: production
    managed-by: kubelint
type: Opaque

stringData:
  DATABASE_USERNAME: "admin"
  DATABASE_PASSWORD: "strong-password"
  JWT_SECRET: "super-secure-jwt-secret"
  API_KEY: "https://xyz.com/api/v1"