package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a production-ready Kubernetes project",
	Args: func(cmd *cobra.Command, args []string) error {
		// No argument provided
		if len(args) == 0 {
			return fmt.Errorf("please provide a project name\nExample: kubelint init my-app")
		}

		// More than one argument provided
		if len(args) > 1 {
			return fmt.Errorf("only one project name is allowed\nExample: kubelint init my-app")
		}

		// Empty project name check
		if args[0] == "" {
			return fmt.Errorf("project name cannot be empty")
		}

		return nil
	},

	Run: func(cmd *cobra.Command, args []string) {
		projectName := args[0]

		fmt.Println("Initializing KubeLint project...")

    fmt.Println()

		createProject(projectName)

		fmt.Println("\nKubeLint project initialized successfully.")
	},
}

func createProject(projectName string) {
	// Root files
	createFile(filepath.Join(projectName, ".kubelint.yaml"), defaultConfig())
	createFile(filepath.Join(projectName, "README.md"), readmeContent(projectName))

	// templates/
	createFile(filepath.Join(projectName, "templates/deployment.yaml"), deploymentContent())
	createFile(filepath.Join(projectName, "templates/service.yaml"), serviceContent())
	createFile(filepath.Join(projectName, "templates/configmap.yaml"), configMapContent())
	createFile(filepath.Join(projectName, "templates/secret.yaml"), secretContent())
	createFile(filepath.Join(projectName, "templates/ingress.yaml"), ingressContent())
	createFile(filepath.Join(projectName, "templates/namespace.yaml"), namespaceContent())

	// environments/
	createFile(
		filepath.Join(projectName, "environments/dev/values.yaml"),
		devValuesContent(),
	)

	createFile(
		filepath.Join(projectName, "environments/prod/values.yaml"),
		prodValuesContent(),
	)
}

func createFile(path string, content string) {
	dir := filepath.Dir(path)

	err := os.MkdirAll(dir, os.ModePerm)
	if err != nil {
		fmt.Printf("✗ Failed to create directory: %s\n", dir)
		return
	}

	_, err = os.Stat(path)
	if err == nil {
		fmt.Printf("✓ %s already exists\n", path)
		return
	}

	err = os.WriteFile(path, []byte(content), 0644)
	if err != nil {
		fmt.Printf("✗ Failed to create file: %s\n", path)
		return
	}

	fmt.Printf("✓ Created %s\n", path)
}

func defaultConfig() string {
	return `rules:
  checkResources: true
  checkProbes: true
  checkSecurity: true

severity:
  failOn: high
`
}

func readmeContent(projectName string) string {
	return "# " + projectName + "\n\nGenerated by KubeLint\n"
}

func deploymentContent() string {
	return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .appName }}
  namespace: {{ .namespace }}
  labels:
    app: {{ .appName }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .appName }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
    spec:
      containers:
        - name: {{ .appName }}
          image: {{ .image.repository }}:{{ .image.tag }}
          ports:
            - containerPort: {{ .service.targetPort }}
          resources:
            requests:
              cpu: "{{ .resources.requests.cpu }}"
              memory: "{{ .resources.requests.memory }}"
            limits:
              cpu: "{{ .resources.limits.cpu }}"
              memory: "{{ .resources.limits.memory }}"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
`
}

func serviceContent() string {
	return `apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  namespace: {{ .namespace }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
  type: {{ .service.type }}
`
}

func configMapContent() string {
	return `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configMap.name }}
  namespace: {{ .namespace }}
data:
  APP_ENV: "{{ .environment }}"
  LOG_LEVEL: "{{ .configMap.logLevel }}"
`
}

func secretContent() string {
	return `apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: {{ .namespace }}
type: Opaque
stringData:
  DB_USERNAME: "{{ .secret.dbUsername }}"
  DB_PASSWORD: "{{ .secret.dbPassword }}"
`
}

func ingressContent() string {
	return `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .ingress.name }}
  namespace: {{ .namespace }}
spec:
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
`
}

func namespaceContent() string {
	return `apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    environment: {{ .environment }}
`
}

func devValuesContent() string {
	return `appName: sample-app
namespace: dev
environment: development

replicas: 1

image:
  repository: nginx
  tag: "latest"

service:
  name: sample-service
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

configMap:
  name: sample-config
  logLevel: debug

secret:
  name: sample-secret
  dbUsername: devuser
  dbPassword: devpassword

ingress:
  name: sample-ingress
  host: dev.sample-app.local
`
}

func prodValuesContent() string {
	return `appName: sample-app
namespace: production
environment: production

replicas: 3

image:
  repository: nginx
  tag: "1.25"

service:
  name: sample-service
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

configMap:
  name: sample-config
  logLevel: info

secret:
  name: sample-secret
  dbUsername: produser
  dbPassword: strongpassword123

ingress:
  name: sample-ingress
  host: sample-app.com
`
}