package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a production-ready Kubernetes project",
	Args: func(cmd *cobra.Command, args []string) error {
		// No argument provided
		if len(args) == 0 {
			return fmt.Errorf("please provide a project name\nExample: kubelint init my-app")
		}

		// More than one argument provided
		if len(args) > 1 {
			return fmt.Errorf("only one project name is allowed\nExample: kubelint init my-app")
		}

		// Empty project name check
		if args[0] == "" {
			return fmt.Errorf("project name cannot be empty")
		}

		return nil
	},

	Run: func(cmd *cobra.Command, args []string) {
		projectName := args[0]

		fmt.Println("Initializing KubeLint project...")

		fmt.Println()

		createProject(projectName)

		fmt.Println("\nKubeLint project initialized successfully.")
	},
}

func createProject(projectName string) {
	// Root files
	createFile(filepath.Join(projectName, ".kubelint.yaml"), defaultConfig())
	createFile(filepath.Join(projectName, "README.md"), readmeContent(projectName))

	// templates/
	createFile(filepath.Join(projectName, "templates/deployment.yaml"), deploymentContent())
	createFile(filepath.Join(projectName, "templates/service.yaml"), serviceContent())
	createFile(filepath.Join(projectName, "templates/configmap.yaml"), configMapContent())
	createFile(filepath.Join(projectName, "templates/secret.yaml"), secretContent())
	createFile(filepath.Join(projectName, "templates/ingress.yaml"), ingressContent())
	createFile(filepath.Join(projectName, "templates/namespace.yaml"), namespaceContent())
	createFile(filepath.Join(projectName, "templates/tls-secret.yaml"), tlsSecretContent())

	// default values for build command
	createFile(
		filepath.Join(projectName, "templates/values.yaml"),
		prodValuesContent(), // default fallback (dev)
	)

	// environments/
	// createFile(
	// 	filepath.Join(projectName, "environments/dev/values.yaml"),
	// 	devValuesContent(),
	// )

	// createFile(
	// 	filepath.Join(projectName, "environments/prod/values.yaml"),
	// 	prodValuesContent(),
	// )
}

func createFile(path string, content string) {
	dir := filepath.Dir(path)

	err := os.MkdirAll(dir, os.ModePerm)
	if err != nil {
		fmt.Printf("✗ Failed to create directory: %s\n", dir)
		return
	}

	_, err = os.Stat(path)
	if err == nil {
		fmt.Printf("✓ %s already exists\n", path)
		return
	}

	err = os.WriteFile(path, []byte(content), 0644)
	if err != nil {
		fmt.Printf("✗ Failed to create file: %s\n", path)
		return
	}

	fmt.Printf("✓ Created %s\n", path)
}

func defaultConfig() string {
	return `rules:
  checkResources: true
  checkProbes: true
  checkSecurity: true

severity:
  failOn: high
`
}

func readmeContent(projectName string) string {
	return "# " + projectName + "\n\n" +
		"Generated by KubeLint\n\n" +

		"## 🚀 Getting Started\n\n" +
		"```bash\n" +
		"kubelint build " + projectName + "\n" +
		"kubelint apply " + projectName + "\n" +
		"```\n\n" +

		"---\n\n" +

		"## 🔐 TLS Certificate Generation\n\n" +
		"This project uses an Ingress with TLS enabled. You need to generate a certificate and key, then encode them in base64.\n\n" +

		"### 1. Generate Self-Signed Certificate\n\n" +
		"```bash\n" +
		"openssl req -x509 -nodes -days 365 -newkey rsa:2048 \\\n" +
		"  -keyout tls.key \\\n" +
		"  -out tls.crt \\\n" +
		"  -subj \"/CN=myapp.example.com/O=myapp\"\n" +
		"```\n\n" +

		"### 2. Convert to Base64\n\n" +
		"```bash\n" +
		"base64 -w 0 tls.crt\n" +
		"base64 -w 0 tls.key\n" +
		"```\n\n" +

		"### 3. Update values.yaml\n\n" +
		"```yaml\n" +
		"tlsSecret:\n" +
		"  data:\n" +
		"    tls.crt: <base64-cert>\n" +
		"    tls.key: <base64-key>\n" +
		"```\n\n" +

		"---\n\n" +

		"## ⚠️ Notes\n\n" +
		"- Self-signed certificates are for development only\n" +
		"- For production, use cert-manager or a trusted CA\n" +
		"- Ensure domain matches Ingress host\n\n" +

		"---\n\n" +

		"## 📦 Generated Resources\n\n" +
		"- Deployment\n" +
		"- Service\n" +
		"- ConfigMap\n" +
		"- Secret\n" +
		"- TLS Secret\n" +
		"- Ingress\n" +
		"- Namespace\n"
}

func deploymentContent() string {
	return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deployment.name }}
  namespace: {{ .deployment.namespace }}
  labels:
{{- range $k, $v := .deployment.labels }}
    {{ $k }}: {{ $v }}
{{- end }}

spec:
  replicas: {{ .deployment.replicas }}

{{- with .deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
{{- end }}

{{- with .deployment.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
{{- end }}

{{- with .deployment.strategy }}
  strategy:
    type: {{ .type }}
{{- with .rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .maxUnavailable }}
      maxSurge: {{ .maxSurge }}
{{- end }}
{{- end }}

  selector:
    matchLabels:
{{- range $k, $v := .deployment.labels }}
      {{ $k }}: {{ $v }}
{{- end }}

  template:
    metadata:
      labels:
{{- range $k, $v := .deployment.labels }}
        {{ $k }}: {{ $v }}
{{- end }}

    spec:

{{- with .deployment.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
{{- end }}

      securityContext:
        runAsNonRoot: {{ .deployment.securityContext.runAsNonRoot }}
        runAsUser: {{ .deployment.securityContext.runAsUser }}
        runAsGroup: {{ .deployment.securityContext.runAsGroup }}
        fsGroup: {{ .deployment.securityContext.fsGroup }}
        seccompProfile:
          type: RuntimeDefault

      containers:
{{- range .deployment.containers }}
        - name: {{ .name }}
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: {{ .imagePullPolicy }}

{{- with .ports }}
          ports:
{{- range . }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
{{- end }}
{{- end }}

{{- with .resources }}
          resources:
            requests:
              cpu: {{ .requests.cpu }}
              memory: {{ .requests.memory }}
            limits:
              cpu: {{ .limits.cpu }}
              memory: {{ .limits.memory }}
{{- end }}

          securityContext:
            privileged: {{ .securityContext.privileged }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: {{ .securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop:
                - ALL

{{- with .envFrom }}
          envFrom:
{{- range . }}
{{- if .configMapRef }}
            - configMapRef:
                name: {{ .configMapRef.name }}
{{- end }}
{{- if .secretRef }}
            - secretRef:
                name: {{ .secretRef.name }}
{{- end }}
{{- end }}
{{- end }}

{{- with .livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
{{- end }}

{{- with .readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
{{- end }}

{{- with .startupProbe }}
          startupProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            failureThreshold: {{ .failureThreshold }}
            periodSeconds: {{ .periodSeconds }}
{{- end }}

{{- with .volumeMounts }}
          volumeMounts:
{{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
{{- end }}
{{- end }}
{{- end }}

{{- with .deployment.volumes }}
      volumes:
{{- range . }}
        - name: {{ .name }}
          emptyDir: {}
{{- end }}
{{- end }}

{{- with .deployment.dnsPolicy }}
      dnsPolicy: {{ . }}
{{- end }}

{{- with .deployment.restartPolicy }}
      restartPolicy: {{ . }}
{{- end }}
`
}

func serviceContent() string {
	return `apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  namespace: {{ .service.namespace }}
{{- with .service.labels }}
  labels:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}

spec:
  type: {{ .service.type }}

  selector:
{{- range $k, $v := .service.selector }}
    {{ $k }}: {{ $v }}
{{- end }}

  ports:
{{- range .service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- with .name }}
      name: {{ . }}
{{- end }}
{{- with .protocol }}
      protocol: {{ . }}
{{- end }}
{{- with .nodePort }}
      nodePort: {{ . }}
{{- end }}
{{- end }}

{{- with .service.sessionAffinity }}
  sessionAffinity: {{ . }}
{{- end }}

{{- with .service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
{{- end }}
`
}

func configMapContent() string {
	return `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configMap.name }}
  namespace: {{ .configMap.namespace }}
{{- with .configMap.labels }}
  labels:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}

data:
{{- range $k, $v := .configMap.data }}
{{- if contains "\n" $v }}
  {{ $k }}: |
{{ $v | indent 4 }}
{{- else }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
`
}

func secretContent() string {
	return `apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: {{ .secret.namespace }}
{{- with .secret.labels }}
  labels:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}

type: {{ .secret.type }}

stringData:
{{- range $k, $v := .secret.stringData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
`
}

func ingressContent() string {
	return `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .ingress.name }}
  namespace: {{ .ingress.namespace }}

{{- with .ingress.labels }}
  labels:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}

{{- with .ingress.annotations }}
  annotations:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}

spec:
{{- with .ingress.ingressClassName }}
  ingressClassName: {{ . }}
{{- end }}

{{- with .ingress.tls }}
  tls:
{{- range . }}
    - hosts:
{{- range .hosts }}
        - {{ . }}
{{- end }}
      secretName: {{ .secretName }}
{{- end }}
{{- end }}

  rules:
{{- range .ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
{{- range .http.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
{{- end }}
{{- end }}
`
}

func tlsSecretContent() string {
	return `apiVersion: v1
kind: Secret
metadata:
  name: {{ .tlsSecret.name }}
  namespace: {{ .tlsSecret.namespace }}

{{- with .tlsSecret.labels }}
  labels:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}

type: {{ .tlsSecret.type }}

data:
  tls.crt: {{ index .tlsSecret.data "tls.crt" }}
  tls.key: {{ index .tlsSecret.data "tls.key" }}`
}

func namespaceContent() string {
	return `apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace.name }}

{{- with .namespace.labels }}
  labels:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}

{{- with .namespace.annotations }}
  annotations:
{{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
`
}

func prodValuesContent() string {
	return `deployment:
  name: my-app
  namespace: production

  labels:
    app: my-app
    tier: backend

  replicas: 3

  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  terminationGracePeriodSeconds: 30

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault

  containers:
    - name: my-app-container
      image:
        repository: myrepo/my-app
        tag: "1.0.0"

      imagePullPolicy: IfNotPresent

      ports:
        - containerPort: 3000
          name: http

      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL

      envFrom:
        - configMapRef:
            name: my-app-config
        - secretRef:
            name: my-app-secret

      livenessProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 10
        periodSeconds: 10

      readinessProbe:
        httpGet:
          path: /ready
          port: http
        initialDelaySeconds: 5
        periodSeconds: 5

      startupProbe:
        httpGet:
          path: /health
          port: http
        failureThreshold: 30
        periodSeconds: 5

      volumeMounts:
        - name: tmp
          mountPath: /tmp

  volumes:
    - name: tmp
      emptyDir: {}

  dnsPolicy: ClusterFirst
  restartPolicy: Always

service:
  name: my-app-service
  namespace: production

  labels:
    app: my-app
    tier: backend

  type: ClusterIP

  selector:
    app: my-app

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

  sessionAffinity: None
  internalTrafficPolicy: Cluster

configMap:
  name: my-app-config
  namespace: production

  labels:
    app: my-app
    tier: backend
    managed-by: kubelint

  data:
    NODE_ENV: "production"
    LOG_LEVEL: "info"
    PORT: "3000"

    APP_CONFIG: |
      {
        "featureFlags": {
          "enableCache": true,
          "enableMetrics": true
        },
        "timeouts": {
          "requestTimeout": 5000,
          "gracefulShutdown": 10000
        }
      }

    API_CONFIG: |
      {
        "baseUrl": "https://api.example.com",
        "retryAttempts": 3
      }

secret:
  name: my-app-secret
  namespace: production

  labels:
    app: my-app
    tier: backend
    managed-by: kubelint

  type: Opaque

  stringData:
    DB_USERNAME: "app_user"
    DB_PASSWORD: "strongpassword123"
    JWT_SECRET: "super-secure-jwt-secret"
    API_KEY: "external-api-key"

ingress:
  name: my-app-ingress
  namespace: production

  labels:
    app: my-app
    tier: backend
    managed-by: kubelint

  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "DENY" always;
      add_header X-XSS-Protection "1; mode=block" always;
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/rewrite-target: /

  ingressClassName: nginx

  tls:
    - hosts:
        - myapp.example.com
      secretName: my-app-tls

  rules:
    - host: myapp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-service
                port:
                  number: 80

tlsSecret:
  name: my-app-tls
  namespace: production

  labels:
    app: my-app
    managed-by: kubelint

  type: kubernetes.io/tls

  data:
    tls.crt: <base64-cert>
    tls.key: <base64-key>

namespace:
  name: production

  labels:
    name: production
    environment: production
    tier: backend
    managed-by: kubelint

  annotations:
    owner: "platform-team"
    purpose: "production workloads"
`
}
