apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: {{ .namespace }}
type: Opaque
stringData:
  DB_USERNAME: "{{ .secret.dbUsername }}"
  DB_PASSWORD: "{{ .secret.dbPassword }}"
